name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/desmanlock
          zip -r desmanlock.zip ./

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ${{ github.workspace }}/custom_components/desmanlock/desmanlock.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
